# Generated by Django 5.1.3 on 2024-12-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='energy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='luminosity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pressure',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
